[package]
name = "libp2p-rpc-behaviour"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.19" }
libp2p = { git = "https://github.com/openmina/rust-libp2p", branch="dan_kad", default-features = false }
mina-p2p-messages = { workspace = true }
