[package]
name = "libp2p-rpc-behaviour"
version = "0.8.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
log = { version = "0.4.19" }
libp2p = { workspace = true }
mina-p2p-messages = { workspace = true }
