[package]
name = "openmina-gossipsub-sandbox"
version = "0.8.2"
edition = "2021"

[dependencies]
env_logger = { version = "0.11.3" }
structopt = { version = "0.3.26" }
log = { version = "0.4.17" }
bs58 = { version = "0.5.0", features = ["check"] }
rand = { version = "0.8.5" }

tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }

libp2p = { workspace = true }
mina-transport = { path = "../transport" }
