[package]
name = "snark"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "snark-bin"
path = "src/bin/main.rs"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
kimchi = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
commitment_dlog = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}
oracle = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a"}

serde = "1.0"
serde_json = { version = "1.0", features = ["float_roundtrip"] }
ark-ff = { version = "0.3", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3", features = [ "parallel" ] }
ark-poly = { version = "0.3", features = [ "parallel" ] }
once_cell = "1.10"
hex = "0.4"
mina-p2p-messages = { git = "https://github.com/name-placeholder/mina-p2p-messages-rs", branch = "main", features = ["hashing"] }
# mina-p2p-messages = { path = "../mina-p2p-messages-rs", features = ["hashing"] }
binprot = { git = "https://github.com/name-placeholder/binprot-rs", rev = "ead5ba916725abf8ab212b89985b47c79d1a006a" }
sha2 = "0.10"
num-bigint = "0.4"

rand = "0.8"
rayon = "1.5"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen-rayon = { version = "1.0", features = ["no-bundler"] }
wasm-bindgen-futures = "0.4"
wasm_thread = { version = "0.2", features = [ "es_modules" ] }

js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }
futures-util = "0.3"

[dev-dependencies]

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = "0.3.0"
